### ISSUE TITLE
Support Extended CAN frames in CAN message mapping

### ISSUE THREAD

**Issue by davefiddes** [davefiddes/openinverter-can-tool#5]
Request from [a768phoenix](https://openinverter.org/forum/viewtopic.php?p=72768#p72768) on the OI forum asking if extended CAN frame IDs can be specified when mapping message parameters. Their BMS uses these frames when talking to the FOCCCI charge controller.

A change has been incorporated into libopeninv in https://github.com/jsphuebner/libopeninv/commit/7c97559435c5a895ed22919b086aed17bbdcfbdd which allows a small range of extended IDs to be mapped using the existing CAN SDO message mapping API. A better API allowing the full 29-bit range of extended IDs would be desirable.

This will affect how CAN IDs are represented internally, the CAN SDO API and in DBC file generation.

**Comment by jsphuebner** [comment]
So the current implementation already supports the full range of extended ids as 32 bits are reserved for the ID specifier.

The issue "solved" by 7c97559 is forcing the CAN hardware to register an extended filter even though the message ID is actually in the 11-bit standard range

**Comment by davefiddes** [comment]
Complete extended CAN frame support has now been implemented for the 0.1.0 release. The support for can maps with  extended frames is limited in libopeninv currently (rx maps with CAN IDs up to 0x7ff). The protocol changes are generic,  have been extensive unit tests and the feature allows maps for either TX or RX and any valid CAN ID. If a device doesn't support a feature it reports `Command or parameter not supported`.
